import { Technology } from "@/types/technology";

const technologiesData: Technology[] = [
  {
    id: 1,
    name: "React",
    href: "https://react.dev/",
    image: "/images/brands/react.svg",
    imageLight: "/images/brands/react-light.svg",
  },
  {
    id: 2,
    name: "NextJs",
    href: "https://nextjs.org/",
    image: "/images/brands/nextjs.svg",
    imageLight: "/images/brands/nextjs-light.svg",
  },
  {
    id: 3,
    name: "VueJs",
    href: "https://vuejs.org/",
    image: "/images/brands/vuejs.svg",
    imageLight: "/images/brands/vuejs-light.svg",
  },
  {
    id: 4,
    name: "Angular",
    href: "https://angular.io/",
    image: "/images/brands/angular.svg",
    imageLight: "/images/brands/angular-light.svg",
  },
  {
    id: 5,
    name: ".NET",
    href: "https://dotnet.microsoft.com/en-us/",
    image: "/images/brands/netcore.svg",
    imageLight: "/images/brands/netcore-light.svg",
  },
  {
    id: 6,
    name: "NodeJs",
    href: "https://nodejs.org/en",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 7,
    name: "Laravel",
    href: "https://laravel.com/",
    image: "/images/brands/laravel.svg",
    imageLight: "/images/brands/laravel-light.svg",
  },
  {
    id: 8,
    name: "Spring Boot",
    href: "https://spring.io/projects/spring-boot",
    image: "/images/brands/spring.svg",
    imageLight: "/images/brands/spring-light.svg",
  },
  {
    id: 9,
    name: "Redux",
    href: "https://redux.js.org/",
    image: "/images/brands/redux.svg",
    imageLight: "/images/brands/redux-light.svg",
  },
  {
    id: 10,
    name: "Tailwind CSS",
    href: "https://tailwindcss.com/",
    image: "/images/brands/tailwind.svg",
    imageLight: "/images/brands/tailwind-light.svg",
  },
  {
    id: 11,
    name: "Material UI",
    href: "https://mui.com/material-ui/",
    image: "/images/brands/mui.svg",
    imageLight: "/images/brands/mui-light.svg",
  },
  {
    id: 12,
    name: "Veutify",
    href: "https://vuetifyjs.com/en/",
    image: "/images/brands/veutify.svg",
    imageLight: "/images/brands/veutify-light.svg",
  },
  {
    id: 13,
    name: "SQL Server",
    href: "https://www.microsoft.com/en-us/sql-server/",
    image: "/images/brands/sqlserver.svg",
    imageLight: "/images/brands/sqlserver-light.svg",
  },
  {
    id: 14,
    name: "MySQL",
    href: "https://www.mysql.com/",
    image: "/images/brands/mysql.svg",
    imageLight: "/images/brands/mysql-light.svg",
  },
  {
    id: 15,
    name: "Azure",
    href: "https://azure.microsoft.com/en-us",
    image: "/images/brands/azure.svg",
    imageLight: "/images/brands/azure-light.svg",
  },
];

export default technologiesData;
