import { Clients } from "@/types/client";


const technologiesData: Clients[] = [
  {
    id: 1,
    name: "MAXTECH ENGINEERING",
    type: "Tax",
    href: "",
    image: "/images/brands/react.svg",
    imageLight: "/images/brands/react-light.svg",
  },
  {
    id: 2,
    name: "Rashida Printing & Packaging",
    type: "Tax",
    href: "",
    image: "/images/brands/nextjs.svg",
    imageLight: "/images/brands/nextjs-light.svg",
  },
  {
    id: 3,
    name: "STUDIO MATIAL",
    type: "Tax",
    href: "",
    image: "/images/brands/vuejs.svg",
    imageLight: "/images/brands/vuejs-light.svg",
  },
  {
    id: 4,
    name: "Britto Art Trust",
    type: "Tax",
    href: "",
    image: "/images/brands/angular.svg",
    imageLight: "/images/brands/angular-light.svg",
  },
  {
    id: 5,
    name: "Friends Air Express",
    type: "Tax",
    href: "",
    image: "/images/brands/netcore.svg",
    imageLight: "/images/brands/netcore-light.svg",
  },
  {
    id: 6,
    name: "Forhad Impex Trade Company",
    type: "Tax",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 7,
    name: "Dewan Food Products Ltd.",
    type: "Tax",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 8,
    name: "UniMed-UniHealth Pharmaceuticals Limited",
    type: "Customs",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 9,
    name: "Ruchikor Agro Food Products Limited",
    type: "Customs",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 10,
    name: "MB Agro Food Products",
    type: "Customs",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 11,
    name: "Lablu Bablu Composite Textiles Ltd",
    type: "VAT",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 11,
    name: "Nexus Trade Centre",
    type: "VAT",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 11,
    name: "Doyen Sourcing Interntional",
    type: "VAT",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
  {
    id: 11,
    name: "Alpha Apparels BD Limited",
    type: "VAT",
    href: "",
    image: "/images/brands/nodejs.svg",
    imageLight: "/images/brands/nodejs-light.svg",
  },
];

export default technologiesData;
